# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: check-tag-templated
        name: Check that the tag workflow has been templated
        language: system
        entry: >
          bash -c "
            TMPL=$(yq e 'explode(.)' .github/workflows/tag.tmpl | md5sum | awk '{print $1}')
            YAML=$(cat .github/workflows/tag.yaml | md5sum | awk '{print $1}')
            if [[ $TMPL != $YAML ]]; then
              exit 1
            fi
          "
        files: ^\.github/workflows/tag.(yaml|tmpl)$
