---

# Optional
#template:
#  application: application-v2.yaml.j2
#  subscription: subscription-v2.yaml.j2

# Required
name: myapp-test
# Required
namespace: test
# Optional
labels:
  tenant: operating-platform
# Required
channel: operating-platform-ch-helm/channel
# Optional
#alias: some-alias
chart:
  # Required
  name: ocp-myapp
  # Required
  version: 0.2.0
  # Optional
  values:
    ccc:
      xxx: zzz
