---

apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: "myapp-test-dev-westeu"
  namespace: "test"
  labels:
    tenant: operating-platform
    acm-app: "myapp"
spec:
  channel: "operating-platform-ch-helm/channel"
  name: "ocp-myapp"
  packageFilter:
    version: "0.2.0"
  placement:
    placementRef:
      name: "dev-westeu"
  packageOverrides:
    - packageName: "ocp-myapp"
      packageAlias: "ocp-myapp"
      packageOverrides:
        - path: spec
          value:
            aaa: bbb
            ccc:
              ddd:
                - eee
                - fff
              xxx: zzz
