name: On merge

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths-ignore:
      - README.md
      - .github/**
      - .gitignore
      - .pre-commit-config.yaml

jobs:
  tag:
    name: Tagging
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Get app name
        id: app
        run: |
          echo ::set-output name=app_name::myapp

      - name: Create and push tag
        run: |
          git tag ${{ steps.app.outputs.app_name }}-$(date '+%Y%m%dT%H%M%S')-dev
          git push --tags
