name: On merge

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths-ignore:
      - README.md
      - .github/**
      - .*

env:
  STEPS_SCRIPT: ./.github/steps.sh

jobs:
  tag:
    name: Tagging
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Get app name
        id: app
        run: |
          $STEPS_SCRIPT merge tag_app

      - name: Get version
        id: version
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.chart.version' ${{ steps.app.outputs.app_name }}/parameters.yaml

      - name: Create and push tag
        run: |
          export APP_NAME='${{ steps.app.outputs.app_name }}'
          export VERSION='${{ steps.version.outputs.result }}'

          $STEPS_SCRIPT merge tag_create_push
