name: On PR

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/**
      - .gitignore
      - .pre-commit-config.yaml

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.3

  validate_res:
    name: Resource validation
    #needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          echo "Validating resources..."

  validate_conf:
    name: Configuration validation
    #needs: validate_res
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          echo "Validating configuration..."

  check_single_app:
    name: Updates to one application only
    #needs: validate_conf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check only one application is changing
        run: |
          NUM_CHANGED=$(git diff origin/master --name-only | egrep -v '^\.github' | grep -Po '^[a-z0-9-]+/' | sort -u | wc -l)

          if [[ "$NUM_CHANGED" != 1 ]]; then
             echo "::error::There must be change exactly to one application (found changes: $NUM_CHANGED)."
             exit 1
          else
             echo '::notice::All good'
          fi
