name: On PR

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.3

  validate_res:
    name: Resource validation
    #needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Something
        run: |
          echo "Validating resources..."

  validate_conf:
    name: Configuration validation
    #needs: validate_res
    runs-on: ubuntu-latest
    steps:
      - name: Something
        run: |
          echo "Validating configuration..."

  check_single_app:
    name: Updates to one application only
    #needs: validate_conf
    runs-on: ubuntu-latest
    steps:
      - name: Something
        run: |
          echo "Checking if only one application is changing..."
