name: On tag
on:
  push:
    tags:
      #  <app>    -<yyyy>  <mm>     <dd>       T<hh>      <mm>      <ss>      -<env>
      - "[a-z0-9]+-202[1-9][01][0-9][0123][0-9]T[012][0-9][0-5][0-9][0-5][0-9]-[a-z]+"
      #  <app-app>          -<yyyy>  <mm>     <dd>       T<hh>      <mm>      <ss>      -<env>
      - "[a-z0-9]+-[a-z0-9]+-202[1-9][01][0-9][0123][0-9]T[012][0-9][0-5][0-9][0-5][0-9]-[a-z]+"
      #  <app-app-app>                -<yyyy>  <mm>     <dd>       T<hh>      <mm>      <ss>      -<env>
      - "[a-z0-9]+-[a-z0-9]+-[a-z0-9]+-202[1-9][01][0-9][0123][0-9]T[012][0-9][0-5][0-9][0-5][0-9]-[a-z]+"
jobs:
  dev:
    name: Dev
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '-dev')
    environment: dev
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Get info from tag
        id: tag
        run: |-
          ENV="${GITHUB_REF##*-}"
          APP="${GITHUB_REF:10:-${#ENV}-17}"
          echo "::set-output name=env_name::$ENV"
          echo "::set-output name=app_name::$APP"
      - name: Print message
        run: |-
          echo "Generating files for app=${{ steps.tag.outputs.app_name }}, env=${{ steps.tag.outputs.env_name }}..."
      - name: Get higher env name
        id: higher_env
        run: |-
          if [[ '${{ steps.tag.outputs.env_name }}' == 'dev' ]]; then
              NAME='lobdev'
          elif [[ '${{ steps.tag.outputs.env_name }}' == 'lobdev' ]]; then
              NAME='uat'
          elif [[ '${{ steps.tag.outputs.env_name }}' == 'uat' ]]; then
              NAME='prod'
          elif [[ '${{ steps.tag.outputs.env_name }}' == 'prod' ]]; then
              NAME=''
          fi

          echo "::set-output name=env_name::$NAME"
      - name: Promote to higer env
        run: |-
          ENV=$(echo '-${{ steps.tag.outputs.env_name }}')
          TAG="${GITHUB_REF##*/}"

          if [[ -n '${{ steps.higher_env.outputs.env_name }}' ]]; then
              git tag "${TAG:0:-${#ENV}}-${{ steps.higher_env.outputs.env_name }}"
              git push --tags
          else
              echo '::notice::End of promotion'
          fi
  lobdev:
    name: LobDev
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '-lobdev')
    environment: lobdev
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Get info from tag
        id: tag
        run: |-
          ENV="${GITHUB_REF##*-}"
          APP="${GITHUB_REF:10:-${#ENV}-17}"
          echo "::set-output name=env_name::$ENV"
          echo "::set-output name=app_name::$APP"
      - name: Print message
        run: |-
          echo "Generating files for app=${{ steps.tag.outputs.app_name }}, env=${{ steps.tag.outputs.env_name }}..."
      - name: Get higher env name
        id: higher_env
        run: |-
          if [[ '${{ steps.tag.outputs.env_name }}' == 'dev' ]]; then
              NAME='lobdev'
          elif [[ '${{ steps.tag.outputs.env_name }}' == 'lobdev' ]]; then
              NAME='uat'
          elif [[ '${{ steps.tag.outputs.env_name }}' == 'uat' ]]; then
              NAME='prod'
          elif [[ '${{ steps.tag.outputs.env_name }}' == 'prod' ]]; then
              NAME=''
          fi

          echo "::set-output name=env_name::$NAME"
      - name: Promote to higer env
        run: |-
          ENV=$(echo '-${{ steps.tag.outputs.env_name }}')
          TAG="${GITHUB_REF##*/}"

          if [[ -n '${{ steps.higher_env.outputs.env_name }}' ]]; then
              git tag "${TAG:0:-${#ENV}}-${{ steps.higher_env.outputs.env_name }}"
              git push --tags
          else
              echo '::notice::End of promotion'
          fi
  uat:
    name: UAT
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '-uat')
    environment: uat
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Get info from tag
        id: tag
        run: |-
          ENV="${GITHUB_REF##*-}"
          APP="${GITHUB_REF:10:-${#ENV}-17}"
          echo "::set-output name=env_name::$ENV"
          echo "::set-output name=app_name::$APP"
      - name: Print message
        run: |-
          echo "Generating files for app=${{ steps.tag.outputs.app_name }}, env=${{ steps.tag.outputs.env_name }}..."
      - name: Get higher env name
        id: higher_env
        run: |-
          if [[ '${{ steps.tag.outputs.env_name }}' == 'dev' ]]; then
              NAME='lobdev'
          elif [[ '${{ steps.tag.outputs.env_name }}' == 'lobdev' ]]; then
              NAME='uat'
          elif [[ '${{ steps.tag.outputs.env_name }}' == 'uat' ]]; then
              NAME='prod'
          elif [[ '${{ steps.tag.outputs.env_name }}' == 'prod' ]]; then
              NAME=''
          fi

          echo "::set-output name=env_name::$NAME"
      - name: Promote to higer env
        run: |-
          ENV=$(echo '-${{ steps.tag.outputs.env_name }}')
          TAG="${GITHUB_REF##*/}"

          if [[ -n '${{ steps.higher_env.outputs.env_name }}' ]]; then
              git tag "${TAG:0:-${#ENV}}-${{ steps.higher_env.outputs.env_name }}"
              git push --tags
          else
              echo '::notice::End of promotion'
          fi
  prod:
    name: Prod
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '-prod')
    environment: prod
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Get info from tag
        id: tag
        run: |-
          ENV="${GITHUB_REF##*-}"
          APP="${GITHUB_REF:10:-${#ENV}-17}"
          echo "::set-output name=env_name::$ENV"
          echo "::set-output name=app_name::$APP"
      - name: Print message
        run: |-
          echo "Generating files for app=${{ steps.tag.outputs.app_name }}, env=${{ steps.tag.outputs.env_name }}..."
      - name: Get higher env name
        id: higher_env
        run: |-
          if [[ '${{ steps.tag.outputs.env_name }}' == 'dev' ]]; then
              NAME='lobdev'
          elif [[ '${{ steps.tag.outputs.env_name }}' == 'lobdev' ]]; then
              NAME='uat'
          elif [[ '${{ steps.tag.outputs.env_name }}' == 'uat' ]]; then
              NAME='prod'
          elif [[ '${{ steps.tag.outputs.env_name }}' == 'prod' ]]; then
              NAME=''
          fi

          echo "::set-output name=env_name::$NAME"
      - name: Promote to higer env
        run: |-
          ENV=$(echo '-${{ steps.tag.outputs.env_name }}')
          TAG="${GITHUB_REF##*/}"

          if [[ -n '${{ steps.higher_env.outputs.env_name }}' ]]; then
              git tag "${TAG:0:-${#ENV}}-${{ steps.higher_env.outputs.env_name }}"
              git push --tags
          else
              echo '::notice::End of promotion'
          fi
