name: On tag

on:
  push:
    tags:
      #  <app>    -<ver>            -<rel> -<env>
      - "[a-z0-9]+-[0-9].[0-9].[0-9]-[0-9]+-[a-z]+"
      #  <app>-<app>        -<ver>            -<rel> -<env>
      - "[a-z0-9]+-[a-z0-9]+-[0-9].[0-9].[0-9]-[0-9]+-[a-z]+"
      #  <app>-<app>-<app>            -<ver>            -<rel> -<env>
      - "[a-z0-9]+-[a-z0-9]+-[a-z0-9]+-[0-9].[0-9].[0-9]-[0-9]+-[a-z]+"

env:
  STEPS_SCRIPT: ./.github/steps.sh

jobs:
  info:
    name: Get info from tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get info
        id: get
        run: |-
          $STEPS_SCRIPT tag info_get

    outputs:
      env_name: ${{ steps.get.outputs.env_name }}
      app_name: ${{ steps.get.outputs.app_name }}
      tag: ${{ steps.get.outputs.tag }}

  deployment:
    name: Deployment into ${{ needs.info.outputs.env_name }}
    runs-on: ubuntu-latest
    environment: ${{ needs.info.outputs.env_name }}
    needs: info
    env:
      APP_NAME: ${{ needs.info.outputs.app_name }}
      ENV_NAME: ${{ needs.info.outputs.env_name }}
      TAG: ${{ needs.info.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Getting the release branch
        uses: actions/checkout@v2
        with:
          ref: release
          path: .release

      - name: Generate ACM Application and Subscription and deploy it
        run: |-
          $STEPS_SCRIPT tag deployment_generate_deploy

      - name: Get next env name
        id: next_env
        run: |-
          $STEPS_SCRIPT tag deployment_next_env

      - name: Promote to next env
        run: |-
          export NEXT_ENV='${{ steps.next_env.outputs.env_name }}'

          $STEPS_SCRIPT tag deployment_promote
